version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: cloud_security_db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: 'cloud_security'

  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080